### ISSUE TITLE
Can't update: "Invalid UPTANE metadata in storage"

### ISSUE THREAD

**Issue by maximeborges** [advancedtelematic/aktualizr#1185] opened 2019-04-18 10:14 UTC
Hello,
I have a few devices using aktualizr. It was working pretty well for a few months now, and I started an old device that wasn't connected to internet for 2 months, and I got this messages:

```
systemd[1]: Started Aktualizr SOTA Client.
aktualizr[225]: Aktualizr version 1.0+gitAUTOINC+a94a15e31f starting
aktualizr[225]: Reading config: "/usr/lib/sota/conf.d/20-sota_autoprov.toml"
aktualizr[225]: Use existing SQL storage: "/var/sota/sql.db"
aktualizr[225]: got SendDeviceData command
aktualizr[225]: got FetchMeta command
aktualizr[225]: got CheckUpdates command
aktualizr[225]: Failed to check director metadata: The targets metadata was expired.
aktualizr[225]: Invalid UPTANE metadata in storage
```

I had to reboot the device to be able to get back the usual FetchMeta and CheckUpdates command, and to be actually able to update my device.

Is there a problem with my configuration or am I missing something ?

**Comment by patrickvacek** [comment] 2019-04-18 10:33
https://github.com/advancedtelematic/aktualizr/commit/a94a15e31f is a pretty old version of aktualizr, and the fact you had to reboot to recover is annoying, but I'm glad you were able to recover in the end. The old targets metadata being expired is not surprising, but that shouldn't have prevented you from checking for updates (as long as the root metadata wasn't also expired). The fetch should have updated all the stored metadata, so something must have gone wrong. The fact that rebooting fixed the problem is strange; I'm not sure what could have changed by rebooting.

It's almost certainly not a problem with your configuration. It could be a bug, but we've reworked so much of that code since then that I don't know if it's worth digging into. We can try to take a look at some point, but it might take a bit before anyone gets a chance to do it.

**Comment by tkfu** [comment] 2019-09-20 10:56
I'm going to close this out, as it's related to a very old version, and it's also an untagged commit somewhere in between the 2018.7 and 2018.8 releases. @maximeborges, if you can reproduce this on a released version that's a bit more current (say, >= 2019.5), please feel free to reopen.

**Closed by tkfu** 2019-09-20 10:56 UTC
