### ISSUE TITLE
More powerful rollback support?

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/aktualizr#1422] opened 2019-10-18 15:51 UTC
My company is starting to look more seriously about rollback support. rollback is geared towards handling a system that can't boot itself. However, we are wondering about scenarios where a device boots and runs, but might be "not functional". "not functional" could mean different things to different people such as:
 * Maybe network-manager is broken and can't communicate with network
 * Maybe an application on your systems is failing to start (Systemd or even docker container)

I'm wondering if you guys have considered some kind of "health check" logic for Aktualizr? Maybe we add something to config like `bootloader.health_check_cmd` and `bootloader.health_check_interval`. Then we could keep a thread running to check for failures and somehow detect a failure and trigger a rollback? I have a feeling this could be a hard thing to do properly/securely.

**Comment by lbonn** [comment] 2019-10-18 16:19
It's something that we have discussed before and it would indeed make rollbacks way more useful.

Your proposal is interesting but we don't necessarily need to have this polling in aktualizr. A first step could be to provide an external command  or api to just set an unhealthy bit somewhere, that could be used by integrators for a health check service at boot, before aktualizr startup.

Depending on the design, aktualizr may or may not have to run after that: the command could already instruct the bootloader and aktualizr could detect what happened at the next boot.

I had the feeling that if something breaks during the device operation, it is not as likely to be caused by a regression requiring a rollback and that fatal defects should be able to be detected early, soon after boot time.

However, maybe some use cases need continuous testing like what you described?

**Comment by mike-sul** [comment] 2019-10-18 16:30
IMHO, both "health check" after an update and a rollback should be outside of libaktualizr and should be part of app/service/system utilizing it. 
My argument is that the former (libaktualizr) does not know all details about an overall app/service/system to determine whether an update was successful while the later (app/service) should know about it.
The fact that system has successfully booted after an ostree update does not mean that an update was successful since a certain app might not work as expected and libaktualizr is not aware about it.

**Comment by doanac** [comment] 2019-10-21 13:53
Thanks for the input. You guys have an interesting perspective. I'm going to spend some time thinking about this and discussing with my team more.

**Comment by ricardosalveti** [comment] 2019-10-21 17:51
One thing we need to consider is that aktualizr itself would be part of the health check, as we need to make sure that it is also functional after the boot. Maybe we could have a way for the system to let aktualizr know if the boot is "to be confirmed" and let the client do the final confirmation (like done with the u-boot environment management)?

**Comment by patrickvacek** [comment] 2019-10-23 13:22
> One thing we need to consider is that aktualizr itself would be part of the health check, as we need to make sure that it is also functional after the boot.

What sorts of things do you think libaktualizr should be checking? Currently, we do a very limited test in `SotaUptaneClient::finalizeAfterReboot()` that the target we installed is what is actually running. I could imagine a networking check or some sort of database integrity check.

**Comment by ricardosalveti** [comment] 2019-10-23 19:07
I believe just internal checking, such as database, as network is really out of scope from aktualizr (base system can check if interface is up and running).

**Comment by zhizhangchen** [comment] 2020-07-12 14:43
Is it possible to have a flag (either through touching a file or exit status of a customizable script) to let actualizr know that the reboot is succefull on the app side. If actualizr finds the flag to be false, it can then rollback the update.

**Comment by patrickvacek** [comment] 2020-07-13 08:56
@zhizhangchen Yes, such a thing is possible, and we've long considered doing something just like that. However, we now have another technique available that might solve your problem: https://github.com/advancedtelematic/meta-updater/pull/734

**Comment by patrickvacek** [comment] 2020-07-30 13:43
Closing for now since we appear to have a decent solution.

**Closed by patrickvacek** 2020-07-30 13:43 UTC
